### ISSUE TITLE
issue: Hacktoberfest banner is not vissible properly on dark mode

### ISSUE THREAD

**Issue by Rahullkumr** [ZoranPandovski/awesome-hacktoberfest-swag#10]
## Please assign me this issue, I would like to work on it under Hacktoberfest label.

![hbnv](https://github.com/ZoranPandovski/awesome-hacktoberfest-swag-2023/assets/42183055/16b95f75-f50b-4127-a98f-351a87fd543f)

**Comment by ZoranPandovski** [comment]
I guess we need transparent logo

**Comment by Rahullkumr** [comment]
# How about this? I guess this looks great. 

## Before

![lol](https://github.com/ZoranPandovski/awesome-hacktoberfest-swag-2023/assets/42183055/ef6550a7-4ea9-4e55-bd6d-16a3f0445bb2)


## After

![Screenshot 2023-10-04 221338](https://github.com/ZoranPandovski/awesome-hacktoberfest-swag-2023/assets/42183055/c70457fa-4222-4bef-8360-3f2444d474e1)

**Comment by ZoranPandovski** [comment]
Sure, let's use that

**Comment by Rahullkumr** [comment]
great to know that, Please assign this issue to me under `Hacktoberfest` label

**Comment by Rahullkumr** [comment]
## or should I directly send the Pull Request (PR)?

**Comment by Rahullkumr** [comment]
finally done
